server:
  port: ${PORT:10100}
spring:
  application:
    name: shop-service
  messages:
    basename: i18n/common,i18n/sso-common

service:
  routes:
    unauth:
      - '/api/auth/register.*'
      - '/api/auth/login.*'
    fallback: 'allow'

#开启sql日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl